### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by SiegeTheDay90** [Justin-Diner/airbnb#5]
- [x]  Contains the following sections: HTML, API Endpoints(Backend)
- [x]  Each route has a description
- [x]  API Endpoint routes contains wildcard variables written in `snake_case`
- [ ]  Routes does not contain superfluous routes
- [ ]  Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    -  probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by SiegeTheDay90** [comment]
Creating a new listing will not require an :id wildcard.

**Comment by Justin-Diner** [comment]
Just checking if other than that, it would cover the superfluous routes?
