### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by SiegeTheDay90** [Justin-Diner/airbnb#6]
- [x]  Frontend routes contains wildcard variables written in `camelCase`
- [x]  Correctly formatted
    - [x]  Routes are displayed with inline coding text (backticks)

**Comment by SiegeTheDay90** [comment]
- What is the purpose of the `/location` frontend route? What will it show?
- The `/users/:userId/edit` route will probably be unecessary.

**Comment by Justin-Diner** [comment]
Location route will show listings based on a location. Such as /newyork. (Part of search feature)

**Comment by SiegeTheDay90** [comment]
Ah, so that might look like `/:locationName` or `/index.html?location=locationName` since the location name is variable and will be used to focus the map.

> Location route will show listings based on a location. Such as /newyork. (Part of search feature)
